secrets:
  infisical_token:
    file: ./infisical_token.txt

services:
  todo-app-backend:
    container_name: todo-app-backend
    build: ./backend
    image: todo-app-backend:Python-3.12-slim
    ports:
      - "8000:8000"
    secrets:
      - infisical_token
    entrypoint: /app/run.sh
    depends_on:
      todo-app-redis:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - ./backend/.gitignore
            - ./backend/run.sh
            - ./backend/core_db/migrations
            - ./backend/backend/*.pyc
            - ./backend/backend/__pycache__
            - ./backend/core_db/*.pyc
            - ./backend/core_db/__pycache__
            - ./backend/backend_api/*.pyc
            - ./backend/backend_api/__pycache__
        - action: rebuild
          path: ./backend/requirements.txt
    networks:
      - to-do-app-network

  todo-app-frontend:
    container_name: todo-app-frontend
    build: ./frontend
    image: todo-app-frontend:Node-20-alpine
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    secrets:
      - infisical_token
    entrypoint: /app/run.sh
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - ./frontend/node_modules
            - ./frontend/.next
            - ./frontend/.gitignore
            - ./frontend/run.sh
        - action: rebuild
          path: ./frontend/package.json
    networks:
      - to-do-app-network

  todo-app-redis:
    build: ./redis
    container_name: todo-app-redis
    image: todo-app-redis:Redis-7
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - to-do-app-network

volumes:
  frontend_node_modules:
  redis-data:

networks:
  to-do-app-network:
    external: true