secrets:
  infisical_token:
    file: ./infisical_token.txt

services:
  todo-app-backend:
    container_name: todo-app-backend
    build: ./backend
    image: todo-app-backend:latest
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    secrets:
      - infisical_token
    entrypoint: /app/run.sh
    depends_on:
      todo-app-redis:
        condition: service_healthy
    networks:
      - to-do-app-network

  todo-app-frontend:
    container_name: todo-app-frontend
    build: ./frontend
    image: todo-app-frontend:latest
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    secrets:
      - infisical_token
    entrypoint: /app/run.sh
    networks:
      - to-do-app-network

  todo-app-redis:
    build: ./redis
    container_name: todo-app-redis
    image: todo-app-redis:7
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - to-do-app-network

volumes:
  frontend_node_modules:
  redis-data:

networks:
  to-do-app-network:
    external: true