secrets:
  infisical_token:
    file: ./infisical_token.txt
  .infisical.json:
    file: ./.infisical.json

services:
  todo-app-backend:
    container_name: todo-app-backend
    build: ./backend
    image: todo-app-backend:Python-3.12-alpine-P
    restart: unless-stopped
    ports:
      - "8000:8000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: /app/run.sh
    depends_on:
      todo-app-redis:
        condition: service_healthy
    networks:
      - web-app-network
    cpus: '1'
    mem_limit: 1g

  todo-app-frontend:
    container_name: todo-app-frontend
    build: ./frontend
    image: todo-app-frontend:Node-20-alpine-P
    restart: unless-stopped
    ports:
      - "3000:3000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: /app/run.sh
    extra_hosts:
      - "todo-app.dev.local:host-gateway"
    networks:
      - web-app-network
    cpus: '0.5'
    mem_limit: 512m

  todo-app-redis:
    build: ./redis
    container_name: todo-app-redis
    image: todo-app-redis:Redis-7.4.2-alpine-P
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - web-app-network
    cpus: '0.3'
    mem_limit: 256m

volumes:
  redis-data:
    driver: local

networks:
  web-app-network:
    external: true