name: Dev Environment Checks

on:
  push:
    branches: [dev-branch]
  pull_request:
    branches: [main]

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Matches package.json runtime
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci # Ensures exact versions from package-lock.json

      - name: Check linting with ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Check code formatting with Prettier
        run: |
          npx prettier --check "**/*.{js,jsx,ts,tsx,css,json}"

  lint-and-test-backend:
    name: Lint and Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create network
        run: docker network create to-do-app-network || true

      - name: Create token file from GitHub secret
        run: echo "${{ secrets.INFISICAL_TOKEN }}" > infisical_token.txt

      - name: Build and start backend services
        run: |
          docker compose up -d --build todo-app-backend todo-app-redis
        env:
          COMPOSE_PROJECT_NAME: to-do-app
          DOCKER_NETWORK: to-do-app-network

      - name: Install linting dependencies
        run: |
          docker exec todo-app-backend sh -c "pip install black==25.1.0 pylint==3.3.4 pylint-django"

      - name: Run backend tests with test database variables
        run: |
          docker exec todo-app-backend sh -c "cd /app && export INFISICAL_TOKEN=\$(cat /run/secrets/infisical_token) 
          && export DB_HOST=localhost && export DB_NAME=testdb && export DB_USER=testuser && export DB_PASSWORD=testpass 
          && export DB_PORT=5432 && infisical run --env=dev --path='/To-do-app/backend' python manage.py test"

      - name: Show logs if tests fail
        if: failure()
        run: docker logs todo-app-backend

      - name: Check linting with Pylint
        run: |
          docker exec todo-app-backend sh -c "cd /app && pylint backend backend_api core_db"

      - name: Check code formatting with Black
        run: |
          docker exec todo-app-backend sh -c "cd /app && black --check ."

      - name: Stop containers and clean up
        if: always()
        run: |
          docker compose down -v
          docker network rm to-do-app-network || true

      - name: Remove token file
        if: always()
        run: rm infisical_token.txt
